apiVersion: v1
kind: Service
metadata:
  name: eduquiz-service
  labels:
    app: eduquiz
spec:
  type: NodePort
  selector:
    app: eduquiz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
